# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Oz2nNIO45tpsTZAHtModrJ_xuKnILei
"""

#Description: This program sends happy birthday emails from a list of birthdays to your friends and family

#Import the libraries 
import datetime
import pandas as pd
import numpy as np
import smtplib
import ssl
from email.mime.text import MIMEText as MT
from email.mime.multipart import MIMEMultipart as MM

#Load the birthday list data
from google.colab import files
files.upload()

#Read in the data
df = pd.read_excel('Birthdays.xlxs (1).xlsx')
#show the data
df

#Create a function to send emails
def email_func(subject, birthday_receiver, name):

  #Store the email addresses for the receiver, and the sender, also store the senders email password
  receiver = birthday_receiver
  sender = 'smthhh@yahoo.com'
  sender_password = ""

  #Creat a MIMEMultipart Object
  msg = MM()
  msg['Subject'] = subject+' '+str(name) +'!'

  #Create the HTML for the message
  HTML ="""
  <html>
     <body>
       <h1> Happy Birthday!</h1>
       <img src = "https://www.funimada.com/assets/images/cards/big/bday-752.gif" alt = "Image" width = "640" height = "360"></img>
       <p> Photo by: Funnimedia</p>
       <h2>
          <p>Hello,<br>
          I hope you have a day and a exciting year ahead! <br><br>
          From;<br>
          Haasini
          </p>
      </h2>
    </body>
  </html>

  """

  #Create a html MIMEText objext
  MTObj = MT(HTML,"html")

  #Attach the MIMEText object into the message container
  msg.attach(MTObj)

  #Create a secure connection with the server and send the email
  #Creat the secure socket layer (SSL) context object
  SSL_context = ssl.create_default_context()
  #Craete the secure Simple Mail Transfer Protocol (SMTP)
  server = smtplib.SMTP_SSL(host = 'smtp.mail.yahoo.com', port=465, context= SSL_context)
  #server = smtplib.SMTP(host = 'smtp.mail.yahoo.com', port=587)
  #Login to the email account
  server.login(sender, sender_password)
  #Send the email
  server.sendmail(sender, receiver, msg.as_string())

#Get todays date

today = datetime.date.today()


#Get the current year
year = today.year

#Loop through the birthday list to send emails to frinds whose birthdays are today
for i in range(0, len(df)):

  #Get the persons month
  month = df['Birth_Month'][i]
  #Get the persons day of birth
  day = df['Birth_Day'][i]
  #Get the persons name
  name = df['Name'][i]
  #Get the persons email adress
  email = df['Email'][i]
  #Get the persons birthdate
  birthdate = datetime.date(int(year), int(month), int(day))

  #Check if today is that persons birthday
  if birthdate == today:
    email_func('Happy Bierthday!', email, name)
    print('sent happy birthday')
else:
  print('Did not send happy birthday')